# Analizar Ventas

In [1]:
from pathlib import Path
import pandas as pd
import json
import datetime as dt
import re
from difflib import get_close_matches

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
print('Importadas ok')
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

Importadas ok

## Ventas

In [2]:
carpeta = "../data/raw/"
file = carpeta + "procesos.parquet"

In [3]:
df_raw = pd.read_parquet(file)
df_raw.head()

,codigo_proyecto,nombre_proyecto,tipo_unidad_principal,codigo_unidad,total_unidades,codigo_unidades_asignadas,nombres_cliente,apellidos_cliente,documento_cliente,origen_proforma,fecha_proforma,codigo_proforma,numero_contrato,fecha_contrato,modalidad_contrato,moneda,tipo_cambio,tipo_financiamiento,banco,situacion_legal,documento_representante,nombres_usuario,username,precio_base_proforma,descuento_venta,precio_venta,aprobador_descuento,nombre,premios,fecha_inicio,fecha_fin,fecha_expiracion,fecha_impresion_contrato,nombre_flujo,estado,completado,total_pagado,total_pendiente,fecha_analisis,fecha_nif,estado_nif,utm_source,utm_medium,utm_campaign,utm_term,utm_content,documento_conyuge,documento_copropietarios,flujo_anulacion,fecha_anulacion,codigo_externo_venta,id,tipo,fecha_actualizacion,codigo_externo_minuta,flujo_error,momento_caida,tipo_cronograma,estado_contrato,devolucion,fecha_devolucion,excedente,observacion_devolucion,motivo_caida,nombres_usuario_aprobador,username_aprobador,cliente_id,usuario_creador,username_creador,usuario_separacion,codigo_externo_entrega,fecha_minuta,proforma_id,penalidad,proceso_anulacion,codigo_externo_anulacion_venta,terminado,paso_actual,estado_personalizado
0,EEUU,Edificio Urbanzen,departamento flat,EEUU-302,2,EEUU-E19,Jan Henri,Larsen,48997555,manual,2025-09-16,2025-05785,NaN,None,Compromiso,PEN,1.000000,hipotecario,NaN,Conyugal,17896123,Yomira Pacheco,ypacheco,712460.00,77460.00,635000.00,ldelsolar,Entrega,None,2026-01-26,2026-01-30,None,None,Proceso de entrega,Activo,Completado,0.00,0.00,2026-01-30,None,NaN,None,None,None,None,None,17896123,NaN,NaN,None,None,21,ENTREGA,2026-01-30,None,False,NaN,NaN,NaN,0.00,None,0.0,NaN,None,NaN,NaN,121739,JOSUE QUIROGA NAVARRO,jquiroga,NaN,None,None,26094,0.00,al iniciar,None,None,Proceso Terminado,None
1,EEUU,Edificio Urbanzen,departamento flat,EEUU-1501,2,EEUU-E26,Katherine Jessy,Bendezú Delgadillo,45347923,manual,2024-03-19,2024-00497,NaN,None,Compromiso,PEN,1.000000,ahorro,Banco de Crédito del Perú (BCP),Propietario Solo,NaN,Nelly Román Villavicencio,nroman,659509.20,72744.51,586764.69,evillanueva,Entrega,None,2026-03-17,2026-03-17,None,None,Proceso de entrega,Activo,Completado,0.00,0.00,2026-03-17,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,68,ENTREGA,2026-03-17,None,False,NaN,NaN,NaN,0.00,None,0.0,NaN,None,NaN,NaN,43624,JOSUE QUIROGA NAVARRO,jquiroga,NaN,None,None,16905,0.00,al iniciar,None,None,Proceso Terminado,None
2,EEUU,Edificio Urbanzen,departamento flat,EEUU-1004,1,NaN,Daniel Ivan,Rivera Perez,07972081,manual,2025-06-08,2025-03322,NaN,None,Compromiso,PEN,1.000000,hipotecario,NaN,Propietario Solo,NaN,Yomira Pacheco,ypacheco,611003.69,66003.69,545000.00,evillanueva,Entrega,None,2026-02-02,2026-01-31,None,None,Proceso de entrega,Activo,Completado,0.00,0.00,2026-01-31,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,27,ENTREGA,2026-02-02,None,False,NaN,NaN,NaN,0.00,None,0.0,NaN,None,NaN,NaN,104639,JOSUE QUIROGA NAVARRO,jquiroga,NaN,None,None,23631,0.00,al iniciar,None,None,Proceso Terminado,None
3,TZ,Tizón y Bueno,departamento flat,TZ-207,2,TZ-10,LAURA CONSUELO,VALDIVIA PACHECO,07261199,manual,2025-10-25,2025-06988,NaN,None,Compromiso,PEN,1.000000,contado,Banco de Crédito del Perú (BCP),Propietario Solo,NaN,Percy Soto,psoto,609782.78,54096.78,555686.00,psoto,Entrega,None,2025-12-11,None,None,None,Proceso de entrega,Activo,No Completado,0.00,0.00,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,7,ENTREGA,2025-12-11,None,False,NaN,NaN,NaN,0.00,None,0.0,NaN,None,NaN,NaN,117871,JOSUE QUIROGA NAVARRO,jquiroga,NaN,None,None,27297,0.00,al iniciar,None,None,Encuestas de propietarios,None
4,EEUU,Edificio Urbanzen,departamento flat,EEUU-802,2,EEUU-E23,NADIA,GUERRA PONCE DE LEON,46230122,manual,2024-07-16,2024-01877,NaN,None,Compromiso,PEN,1.000000,hipotecario,Banco de Crédito del Perú (BCP),Propietario Solo,NaN,Nelly Román Villavicencio,nroman,611070.02,56237.00,554833.02,nroman,Entrega,None,2026-05-19,2026-05-18,None,None,Proceso de entrega,Activo,Completado,0.00,0.00,2026-05-18,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,79,ENTREGA,2026-05-19,None,False,NaN,NaN,NaN,0.00,None,0.0,NaN,None,NaN,NaN,54874,JOSUE QUIROGA NAVARRO,jquiroga,NaN,None,None,18285,0.00,al iniciar,None,None,Proceso Terminado,None

In [4]:
df = df_raw.copy()
def recordar_basicos():
    print('Aqui pondré los basicos de python, de lo que sé de memoria')
    print("type - es preguntarle lo basico:")
    print(f'Quien eres: {type(df)}') #"info
    if isinstance(df, pd.DataFrame):
    #if type(df) =="<class 'pandas.DataFrame'>":
        t="sí es un df"
    else:
        t = "no es df"
    print(t)
    print('De qué tamaño eres?')
    col, filas = df.shape[0], df.shape[1]
    print(f'En el df existe {col} columnas y {filas} filas.')
    print('Qué variables tienes?')
    variables = df.columns.to_list()
    print(f'Las variables ({len(variables)}) que tengo son: {variables}')
    #print('De ellas, ')
    #print(f'Y mis filas van de {}')
    df.info()

recordar_basicos()

Aqui pondré los basicos de python, de lo que sé de memoria
type - es preguntarle lo basico:
Quien eres: <class 'pandas.DataFrame'>
sí es un df
De qué tamaño eres?
En el df existe 4830 columnas y 79 filas.
Qué variables tienes?
Las variables (79) que tengo son: ['codigo_proyecto', 'nombre_proyecto', 'tipo_unidad_principal', 'codigo_unidad', 'total_unidades', 'codigo_unidades_asignadas', 'nombres_cliente', 'apellidos_cliente', 'documento_cliente', 'origen_proforma', 'fecha_proforma', 'codigo_proforma', 'numero_contrato', 'fecha_contrato', 'modalidad_contrato', 'moneda', 'tipo_cambio', 'tipo_financiamiento', 'banco', 'situacion_legal', 'documento_representante', 'nombres_usuario', 'username', 'precio_base_proforma', 'descuento_venta', 'precio_venta', 'aprobador_descuento', 'nombre', 'premios', 'fecha_inicio', 'fecha_fin', 'fecha_expiracion', 'fecha_impresion_contrato', 'nombre_flujo', 'estado', 'completado', 'total_pagado', 'total_pendiente', 'fecha_analisis', 'fecha_nif', 'estado_nif', 'utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content', 'documento_conyuge', 'documento_copropietarios', 'flujo_anulacion', 'fecha_anulacion', 'codigo_externo_venta', 'id', 'tipo', 'fecha_actualizacion', 'codigo_externo_minuta', 'flujo_error', 'momento_caida', 'tipo_cronograma', 'estado_contrato', 'devolucion', 'fecha_devolucion', 'excedente', 'observacion_devolucion', 'motivo_caida', 'nombres_usuario_aprobador', 'username_aprobador', 'cliente_id', 'usuario_creador', 'username_creador', 'usuario_separacion', 'codigo_externo_entrega', 'fecha_minuta', 'proforma_id', 'penalidad', 'proceso_anulacion', 'codigo_externo_anulacion_venta', 'terminado', 'paso_actual', 'estado_personalizado']
<class 'pandas.DataFrame'>
RangeIndex: 4830 entries, 0 to 4829
Data columns (total 79 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   codigo_proyecto                 4830 non-null   str
 1   nombre_proyecto                 4830 non-null   str
 2   tipo_unidad_principal           4830 non-null   str
 3   codigo_unidad                   4830 non-null   str
 4   total_unidades                  4830 non-null   int64
 5   codigo_unidades_asignadas       1108 non-null   str
 6   nombres_cliente                 4830 non-null   str
 7   apellidos_cliente               4824 non-null   str
 8   documento_cliente               4830 non-null   str
 9   origen_proforma                 4830 non-null   str
 10  fecha_proforma                  4830 non-null   object
 11  codigo_proforma                 4830 non-null   str
 12  numero_contrato                 9 non-null      str
 13  fecha_contrato                  0 non-null      object
 14  modalidad_contrato              4830 non-null   str
 15  moneda                          4830 non-null   str
 16  tipo_cambio                     4830 non-null   object
 17  tipo_financiamiento             4830 non-null   str
 18  banco                           3005 non-null   str
 19  situacion_legal                 4830 non-null   str
 20  documento_representante         224 non-null    str
 21  nombres_usuario                 4830 non-null   str
 22  username                        4830 non-null   str
 23  precio_base_proforma            4830 non-null   object
 24  descuento_venta                 4830 non-null   object
 25  precio_venta                    4830 non-null   object
 26  aprobador_descuento             3104 non-null   str
 27  nombre                          4830 non-null   str
 28  premios                         0 non-null      object
 29  fecha_inicio                    4830 non-null   object
 30  fecha_fin                       3841 non-null   object
 31  fecha_expiracion                4752 non-null   object
 32  fecha_impresion_contrato        73 non-null     object
 33  nombre_flujo                    4798 non-null   str
 34  estado                          4830 non-null   str
 35  completado                      4830 non-null   str
 36  total_pagado                    4725 non-null   object
 37  total_pendiente                 4725 non-null   object
 38  fecha_analisis                  4572 non-null   object
 39  fecha_nif                       0 non-null      object
 40  estado_nif                      4752 non-null   str
 41  utm_source                      0 non-null      object
 42  utm_medium                      0 non-null      object
 43  utm_campaign                    0 non-null      object
 44  utm_term                        0 non-null      object
 45  utm_content                     0 non-null      object
 46  documento_conyuge               807 non-null    str
 47  documento_copropietarios        46 non-null     str
 48  flujo_anulacion                 958 non-null    str
 49  fecha_anulacion                 987 non-null    object
 50  codigo_externo_venta            0 non-null      object
 51  id                              4830 non-null   int64
 52  tipo                            4830 non-null   str
 53  fecha_actualizacion             4830 non-null   object
 54  codigo_externo_minuta           0 non-null      object
 55  flujo_error                     4798 non-null   object
 56  momento_caida                   416 non-null    str
 57  tipo_cronograma                 940 non-null    str
 58  estado_contrato                 4752 non-null   str
 59  devolucion                      4830 non-null   object
 60  fecha_devolucion                6 non-null      object
 61  excedente                       386 non-null    float64
 62  observacion_devolucion          193 non-null    str
 63  motivo_caida                    0 non-null      object
 64  nombres_usuario_aprobador       3788 non-null   str
 65  username_aprobador              3788 non-null   str
 66  cliente_id                      4830 non-null   int64
 67  usuario_creador                 4830 non-null   str
 68  username_creador                4830 non-null   str
 69  usuario_separacion              4085 non-null   str
 70  codigo_externo_entrega          0 non-null      object
 71  fecha_minuta                    0 non-null      object
 72  proforma_id                     4830 non-null   int64
 73  penalidad                       4830 non-null   object
 74  proceso_anulacion               4830 non-null   str
 75  codigo_externo_anulacion_venta  0 non-null      object
 76  terminado                       0 non-null      object
 77  paso_actual                     4830 non-null   str
 78  estado_personalizado            0 non-null      object
dtypes: float64(1), int64(4), object(34), str(40)
memory usage: 4.5+ MB

## Contarme como fechas

In [5]:
import pandas as pd


def describir_fechas(df, texto_busqueda="fecha", dayfirst=True):
    """
    Encuentra columnas relacionadas con fechas y devuelve:
    - tipo original;
    - cantidad de registros;
    - fechas válidas e inválidas;
    - fecha mínima y máxima;
    - amplitud temporal en días.

    No modifica el DataFrame original.
    """

    # Busca columnas que contengan "fecha"
    columnas_fecha = [
        columna
        for columna in df.columns
        if texto_busqueda.lower() in columna.lower()
        or pd.api.types.is_datetime64_any_dtype(df[columna])
    ]

    if not columnas_fecha:
        print(
            f"No encontré columnas que contengan '{texto_busqueda}' "
            "ni columnas reconocidas como datetime."
        )
        return pd.DataFrame()

    resumen = []

    for columna in columnas_fecha:

        serie_original = df[columna]

        # Intenta convertir los valores a fecha
        serie_fecha = pd.to_datetime(
            serie_original,
            errors="coerce",
            dayfirst=dayfirst
        )

        registros_con_dato = serie_original.notna().sum()
        fechas_validas = serie_fecha.notna().sum()
        fechas_invalidas = registros_con_dato - fechas_validas

        fecha_minima = serie_fecha.min()
        fecha_maxima = serie_fecha.max()

        if pd.notna(fecha_minima) and pd.notna(fecha_maxima):
            rango_dias = (fecha_maxima - fecha_minima).days
        else:
            rango_dias = None

        resumen.append({
            "columna": columna,
            "tipo_original": str(serie_original.dtype),
            "total_filas": len(df),
            "registros_con_dato": registros_con_dato,
            "fechas_validas": fechas_validas,
            "fechas_invalidas": fechas_invalidas,
            "valores_nulos": serie_original.isna().sum(),
            "fecha_inicio": fecha_minima,
            "fecha_final": fecha_maxima,
            "rango_dias": rango_dias
        })

    resultado = pd.DataFrame(resumen)

    return resultado.sort_values(
        by="fecha_inicio",
        na_position="last"
    ).reset_index(drop=True)

resumen_fechas = describir_fechas(df)

resumen_fechas

,columna,tipo_original,total_filas,registros_con_dato,fechas_validas,fechas_invalidas,valores_nulos,fecha_inicio,fecha_final,rango_dias
0,fecha_inicio,object,4830,4830,4830,0,0,2018-03-16,2026-07-12,3040.0
1,fecha_fin,object,4830,3841,3841,0,989,2018-03-16,2026-07-12,3040.0
2,fecha_analisis,object,4830,4572,4572,0,258,2018-03-16,2026-07-12,3040.0
3,fecha_proforma,object,4830,4830,4830,0,0,2019-10-02,2026-07-12,2475.0
4,fecha_actualizacion,object,4830,4830,4830,0,0,2019-10-02,2026-07-12,2475.0
5,fecha_expiracion,object,4830,4752,4752,0,78,2019-10-03,2026-08-09,2502.0
6,fecha_anulacion,object,4830,987,987,0,3843,2019-11-08,2026-07-10,2436.0
7,fecha_impresion_contrato,object,4830,73,73,0,4757,2021-01-15,2026-05-26,1957.0
8,fecha_devolucion,object,4830,6,6,0,4824,2024-09-19,2026-05-26,614.0
9,fecha_contrato,object,4830,0,0,0,4830,NaT,NaT,NaN
10,fecha_nif,object,4830,0,0,0,4830,NaT,NaT,NaN
11,fecha_minuta,object,4830,0,0,0,4830,NaT,NaT,NaN

In [6]:
def contar_historia_fechas(df):
    resumen = describir_fechas(df)

    if resumen.empty:
        return

    print("Hola, estas son las columnas de fecha que encontré:\n")

    for _, fila in resumen.iterrows():

        columna = fila["columna"]
        inicio = fila["fecha_inicio"]
        final = fila["fecha_final"]
        validas = fila["fechas_validas"]
        invalidas = fila["fechas_invalidas"]
        nulos = fila["valores_nulos"]

        if pd.isna(inicio) or pd.isna(final):
            print(
                f"• {columna}: no pude encontrar un rango de fechas válido."
            )
            continue

        print(
            f"• En '{columna}', mi historia comienza el "
            f"{inicio:%d/%m/%Y} y termina el {final:%d/%m/%Y}."
        )

        print(
            f"  Reconocí {validas:,} fechas válidas, "
            f"{invalidas:,} valores inválidos y "
            f"{nulos:,} valores nulos.\n"
        )

contar_historia_fechas(df)

Hola, estas son las columnas de fecha que encontré:

• En 'fecha_inicio', mi historia comienza el 16/03/2018 y termina el 12/07/2026.
  Reconocí 4,830 fechas válidas, 0 valores inválidos y 0 valores nulos.

• En 'fecha_fin', mi historia comienza el 16/03/2018 y termina el 12/07/2026.
  Reconocí 3,841 fechas válidas, 0 valores inválidos y 989 valores nulos.

• En 'fecha_analisis', mi historia comienza el 16/03/2018 y termina el 12/07/2026.
  Reconocí 4,572 fechas válidas, 0 valores inválidos y 258 valores nulos.

• En 'fecha_proforma', mi historia comienza el 02/10/2019 y termina el 12/07/2026.
  Reconocí 4,830 fechas válidas, 0 valores inválidos y 0 valores nulos.

• En 'fecha_actualizacion', mi historia comienza el 02/10/2019 y termina el 12/07/2026.
  Reconocí 4,830 fechas válidas, 0 valores inválidos y 0 valores nulos.

• En 'fecha_expiracion', mi historia comienza el 03/10/2019 y termina el 09/08/2026.
  Reconocí 4,752 fechas válidas, 0 valores inválidos y 78 valores nulos.

• En 'fecha_anulacion', mi historia comienza el 08/11/2019 y termina el 10/07/2026.
  Reconocí 987 fechas válidas, 0 valores inválidos y 3,843 valores nulos.

• En 'fecha_impresion_contrato', mi historia comienza el 15/01/2021 y termina el 26/05/2026.
  Reconocí 73 fechas válidas, 0 valores inválidos y 4,757 valores nulos.

• En 'fecha_devolucion', mi historia comienza el 19/09/2024 y termina el 26/05/2026.
  Reconocí 6 fechas válidas, 0 valores inválidos y 4,824 valores nulos.

• fecha_contrato: no pude encontrar un rango de fechas válido.
• fecha_nif: no pude encontrar un rango de fechas válido.
• fecha_minuta: no pude encontrar un rango de fechas válido.

## gráfico de fechas

In [7]:
import plotly.express as px


def graficar_rangos_fechas(df):
    resumen = describir_fechas(df)

    resumen = resumen.dropna(
        subset=["fecha_inicio", "fecha_final"]
    )

    if resumen.empty:
        print("No hay columnas con rangos de fechas válidos.")
        return

    figura = px.timeline(
        resumen,
        x_start="fecha_inicio",
        x_end="fecha_final",
        y="columna",
        title="Cobertura temporal de las columnas de fecha",
        hover_data={
            "fechas_validas": ":,",
            "fechas_invalidas": ":,",
            "valores_nulos": ":,",
            "rango_dias": ":,"
        }
    )

    figura.update_yaxes(
        title="Columnas",
        autorange="reversed"
    )

    figura.update_xaxes(
        title="Periodo cubierto",
        showgrid=True
    )

    figura.update_layout(
        template="plotly_white",
        title_x=0.02,
        height=max(400, len(resumen) * 65),
        margin=dict(l=40, r=40, t=80, b=40),
        hoverlabel=dict(
            bgcolor="white",
            font_size=13
        )
    )

    figura.show()

In [8]:
graficar_rangos_fechas(df)

## Preparar distribucion de fechas

In [15]:
def preparar_distribucion_fechas(
    df,
    frecuencia="M",
    texto_busqueda="fecha",
    dayfirst=True
):
    """
    frecuencia:
    D = día
    W = semana
    M = mes
    Q = trimestre
    Y = año
    """

    columnas_fecha = [
        columna
        for columna in df.columns
        if texto_busqueda.lower() in columna.lower()
        or pd.api.types.is_datetime64_any_dtype(df[columna])
    ]

    distribuciones = []

    for columna in columnas_fecha:

        fechas = pd.to_datetime(
            df[columna],
            errors="coerce",
            dayfirst=dayfirst
        ).dropna()

        if fechas.empty:
            continue

        distribucion = (
            fechas
            .dt.to_period(frecuencia)
            .value_counts()
            .sort_index()
            .rename_axis("periodo")
            .reset_index(name="cantidad")
        )

        distribucion["fecha"] = distribucion["periodo"].dt.start_time
        distribucion["columna"] = columna

        distribuciones.append(
            distribucion[["fecha", "columna", "cantidad"]]
        )

    if not distribuciones:
        return pd.DataFrame(
            columns=["fecha", "columna", "cantidad"]
        )

    return pd.concat(
        distribuciones,
        ignore_index=True
    )
preparar_distribucion_fechas(df)

         fecha                   columna  cantidad
0   2019-10-01            fecha_proforma        15
1   2019-11-01            fecha_proforma         4
2   2019-12-01            fecha_proforma         5
3   2020-01-01            fecha_proforma         6
4   2020-02-01            fecha_proforma        22
5   2020-03-01            fecha_proforma        37
6   2020-06-01            fecha_proforma         3
7   2020-09-01            fecha_proforma        10
8   2020-10-01            fecha_proforma         8
9   2021-07-01            fecha_proforma        23
10  2021-08-01            fecha_proforma        12
11  2021-09-01            fecha_proforma        91
12  2021-10-01            fecha_proforma        79
13  2021-11-01            fecha_proforma        35
14  2021-12-01            fecha_proforma        46
15  2022-01-01            fecha_proforma        19
16  2022-02-01            fecha_proforma       144
17  2022-03-01            fecha_proforma       114
18  2022-04-01            fecha_proforma        41
19  2022-05-01            fecha_proforma        24
20  2022-06-01            fecha_proforma        18
21  2022-07-01            fecha_proforma        14
22  2022-08-01            fecha_proforma        54
23  2022-09-01            fecha_proforma        64
24  2022-10-01            fecha_proforma        35
25  2022-11-01            fecha_proforma        21
26  2022-12-01            fecha_proforma        11
27  2023-01-01            fecha_proforma        18
28  2023-02-01            fecha_proforma         5
29  2023-03-01            fecha_proforma        19
30  2023-05-01            fecha_proforma         5
31  2023-06-01            fecha_proforma        30
32  2023-07-01            fecha_proforma         6
33  2023-08-01            fecha_proforma         9
34  2023-09-01            fecha_proforma        29
35  2023-10-01            fecha_proforma        16
36  2023-11-01            fecha_proforma        29
37  2023-12-01            fecha_proforma        61
38  2024-01-01            fecha_proforma       692
39  2024-02-01            fecha_proforma        19
40  2024-03-01            fecha_proforma        35
41  2024-04-01            fecha_proforma        40
42  2024-05-01            fecha_proforma        91
43  2024-06-01            fecha_proforma        61
44  2024-07-01            fecha_proforma        45
45  2024-08-01            fecha_proforma        53
46  2024-09-01            fecha_proforma        68
47  2024-10-01            fecha_proforma        57
48  2024-11-01            fecha_proforma       105
49  2024-12-01            fecha_proforma        64
50  2025-01-01            fecha_proforma       101
51  2025-02-01            fecha_proforma        65
52  2025-03-01            fecha_proforma       138
53  2025-04-01            fecha_proforma        85
54  2025-05-01            fecha_proforma        92
55  2025-06-01            fecha_proforma        98
56  2025-07-01            fecha_proforma       149
57  2025-08-01            fecha_proforma       141
58  2025-09-01            fecha_proforma       195
59  2025-10-01            fecha_proforma       112
60  2025-11-01            fecha_proforma       155
61  2025-12-01            fecha_proforma       104
62  2026-01-01            fecha_proforma       157
63  2026-02-01            fecha_proforma       142
64  2026-03-01            fecha_proforma       200
65  2026-04-01            fecha_proforma       103
66  2026-05-01            fecha_proforma       171
67  2026-06-01            fecha_proforma        85
68  2026-07-01            fecha_proforma        25
69  2018-03-01              fecha_inicio         4
70  2018-06-01              fecha_inicio         4
71  2018-08-01              fecha_inicio         4
72  2018-09-01              fecha_inicio         2
73  2019-01-01              fecha_inicio         2
74  2019-02-01              fecha_inicio         4
75  2019-03-01              fecha_inicio         4
76  2019-04-01              fecha_inicio         6
77  2019-06-01              fecha_inicio        18
78  2019-07-01              fecha_inicio        11
79  2019-08-01              fecha_inicio         8
80  2019-09-01              fecha_inicio        26
81  2019-10-01              fecha_inicio        11
82  2019-11-01              fecha_inicio        18
83  2019-12-01              fecha_inicio         8
84  2020-01-01              fecha_inicio         2
85  2020-02-01              fecha_inicio        18
86  2020-03-01              fecha_inicio        36
87  2020-05-01              fecha_inicio         2
88  2020-06-01              fecha_inicio         7
89  2020-07-01              fecha_inicio         4
90  2020-08-01              fecha_inicio         2
91  2020-09-01              fecha_inicio         7
92  2020-10-01              fecha_inicio         6
93  2020-11-01              fecha_inicio         4
94  2020-12-01              fecha_inicio         4
95  2021-01-01              fecha_inicio        15
96  2021-02-01              fecha_inicio        11
97  2021-03-01              fecha_inicio        14
98  2021-04-01              fecha_inicio        17
99  2021-05-01              fecha_inicio         8
100 2021-06-01              fecha_inicio        16
101 2021-07-01              fecha_inicio        36
102 2021-08-01              fecha_inicio        20
103 2021-09-01              fecha_inicio        34
104 2021-10-01              fecha_inicio        54
105 2021-11-01              fecha_inicio        36
106 2021-12-01              fecha_inicio        45
107 2022-01-01              fecha_inicio        38
108 2022-02-01              fecha_inicio        57
109 2022-03-01              fecha_inicio        41
110 2022-04-01              fecha_inicio        33
111 2022-05-01              fecha_inicio        39
112 2022-06-01              fecha_inicio        18
113 2022-07-01              fecha_inicio        28
114 2022-08-01              fecha_inicio        27
115 2022-09-01              fecha_inicio        58
116 2022-10-01              fecha_inicio        36
117 2022-11-01              fecha_inicio        36
118 2022-12-01              fecha_inicio        10
119 2023-01-01              fecha_inicio        11
120 2023-02-01              fecha_inicio         8
121 2023-03-01              fecha_inicio        14
122 2023-04-01              fecha_inicio         8
123 2023-05-01              fecha_inicio         9
124 2023-06-01              fecha_inicio        12
125 2023-07-01              fecha_inicio        13
126 2023-08-01              fecha_inicio        16
127 2023-09-01              fecha_inicio        31
128 2023-10-01              fecha_inicio        26
129 2023-11-01              fecha_inicio        32
130 2023-12-01              fecha_inicio        22
131 2024-01-01              fecha_inicio       689
132 2024-02-01              fecha_inicio        26
133 2024-03-01              fecha_inicio        25
134 2024-04-01              fecha_inicio        35
135 2024-05-01              fecha_inicio        63
136 2024-06-01              fecha_inicio        53
137 2024-07-01              fecha_inicio        48
138 2024-08-01              fecha_inicio        56
139 2024-09-01              fecha_inicio        84
140 2024-10-01              fecha_inicio        40
141 2024-11-01              fecha_inicio       134
142 2024-12-01              fecha_inicio        44
143 2025-01-01              fecha_inicio       111
144 2025-02-01              fecha_inicio        59
145 2025-03-01              fecha_inicio       110
146 2025-04-01              fecha_inicio       101
147 2025-05-01              fecha_inicio        89
148 2025-06-01              fecha_inicio        80
149 2025-07-01              fecha_inicio       131
150 2025-08-01              fecha_inicio       118
151 2025-09-01              fecha_inicio       189
152 2025-10-01              fecha_inicio       140
153 2025-11-01              fecha_inicio       137
154 2025-12-01              fecha_inicio       109
155 2026-01-01              fecha_inicio       131
156 2026-02-01              fecha_inicio       119
157 2026-03-01              fecha_inicio       160
158 2026-04-01              fecha_inicio       178
159 2026-05-01              fecha_inicio       162
160 2026-06-01              fecha_inicio       203
161 2026-07-01              fecha_inicio        55
162 2018-03-01                 fecha_fin         4
163 2018-06-01                 fecha_fin         4
164 2018-08-01                 fecha_fin         4
165 2018-09-01                 fecha_fin         2
166 2019-01-01                 fecha_fin         2
167 2019-02-01                 fecha_fin         4
168 2019-03-01                 fecha_fin         4
169 2019-04-01                 fecha_fin         6
170 2019-06-01                 fecha_fin        18
171 2019-07-01                 fecha_fin        11
172 2019-08-01                 fecha_fin         8
173 2019-09-01                 fecha_fin        26
174 2019-10-01                 fecha_fin         5
175 2019-11-01                 fecha_fin        15
176 2019-12-01                 fecha_fin         3
177 2020-02-01                 fecha_fin         8
178 2020-03-01                 fecha_fin         5
179 2020-05-01                 fecha_fin         2
180 2020-06-01                 fecha_fin         7
181 2020-07-01                 fecha_fin         4
182 2020-08-01                 fecha_fin         2
183 2020-10-01                 fecha_fin         3
184 2020-11-01                 fecha_fin         3
185 2020-12-01                 fecha_fin         4
186 2021-01-01                 fecha_fin        14
187 2021-02-01                 fecha_fin        11
188 2021-03-01                 fecha_fin        14
189 2021-04-01                 fecha_fin        17
190 2021-05-01                 fecha_fin         8
191 2021-06-01                 fecha_fin        16
192 2021-07-01                 fecha_fin        18
193 2021-08-01                 fecha_fin        20
194 2021-09-01                 fecha_fin        34
195 2021-10-01                 fecha_fin        39
196 2021-11-01                 fecha_fin        35
197 2021-12-01                 fecha_fin        47
198 2022-01-01                 fecha_fin        40
199 2022-02-01                 fecha_fin        55
200 2022-03-01                 fecha_fin        36
201 2022-04-01                 fecha_fin        25
202 2022-05-01                 fecha_fin        38
203 2022-06-01                 fecha_fin        18
204 2022-07-01                 fecha_fin        26
205 2022-08-01                 fecha_fin        22
206 2022-09-01                 fecha_fin        48
207 2022-10-01                 fecha_fin        34
208 2022-11-01                 fecha_fin        35
209 2022-12-01                 fecha_fin        10
210 2023-01-01                 fecha_fin        10
211 2023-02-01                 fecha_fin         8
212 2023-03-01                 fecha_fin        12
213 2023-04-01                 fecha_fin         8
214 2023-05-01                 fecha_fin         7
215 2023-06-01                 fecha_fin        12
216 2023-07-01                 fecha_fin        13
217 2023-08-01                 fecha_fin        14
218 2023-09-01                 fecha_fin        28
219 2023-10-01                 fecha_fin        19
220 2023-11-01                 fecha_fin        20
221 2023-12-01                 fecha_fin        16
222 2024-01-01                 fecha_fin       679
223 2024-02-01                 fecha_fin        20
224 2024-03-01                 fecha_fin        14
225 2024-04-01                 fecha_fin        30
226 2024-05-01                 fecha_fin        34
227 2024-06-01                 fecha_fin        43
228 2024-07-01                 fecha_fin        38
229 2024-08-01                 fecha_fin        52
230 2024-09-01                 fecha_fin        78
231 2024-10-01                 fecha_fin        13
232 2024-11-01                 fecha_fin       137
233 2024-12-01                 fecha_fin        41
234 2025-01-01                 fecha_fin       104
235 2025-02-01                 fecha_fin        42
236 2025-03-01                 fecha_fin        72
237 2025-04-01                 fecha_fin        69
238 2025-05-01                 fecha_fin        59
239 2025-06-01                 fecha_fin        64
240 2025-07-01                 fecha_fin        91
241 2025-08-01                 fecha_fin        55
242 2025-09-01                 fecha_fin       188
243 2025-10-01                 fecha_fin       123
244 2025-11-01                 fecha_fin       105
245 2025-12-01                 fecha_fin        76
246 2026-01-01                 fecha_fin        41
247 2026-02-01                 fecha_fin        42
248 2026-03-01                 fecha_fin        57
249 2026-04-01                 fecha_fin        82
250 2026-05-01                 fecha_fin        74
251 2026-06-01                 fecha_fin       260
252 2026-07-01                 fecha_fin        77
253 2019-10-01          fecha_expiracion         7
254 2019-11-01          fecha_expiracion         3
255 2019-12-01          fecha_expiracion         7
256 2020-01-01          fecha_expiracion         3
257 2020-02-01          fecha_expiracion        14
258 2020-03-01          fecha_expiracion        32
259 2020-06-01          fecha_expiracion         1
260 2020-09-01          fecha_expiracion         6
261 2020-10-01          fecha_expiracion         4
262 2020-11-01          fecha_expiracion         3
263 2021-07-01          fecha_expiracion        11
264 2021-08-01          fecha_expiracion        17
265 2021-09-01          fecha_expiracion        99
266 2021-10-01          fecha_expiracion        47
267 2021-11-01          fecha_expiracion        52
268 2021-12-01          fecha_expiracion        40
269 2022-01-01          fecha_expiracion        26
270 2022-02-01          fecha_expiracion       133
271 2022-03-01          fecha_expiracion       124
272 2022-04-01          fecha_expiracion        43
273 2022-05-01          fecha_expiracion        30
274 2022-06-01          fecha_expiracion        28
275 2022-07-01          fecha_expiracion        19
276 2022-08-01          fecha_expiracion        39
277 2022-09-01          fecha_expiracion        39
278 2022-10-01          fecha_expiracion        44
279 2022-11-01          fecha_expiracion        33
280 2022-12-01          fecha_expiracion        25
281 2023-01-01          fecha_expiracion        22
282 2023-02-01          fecha_expiracion         2
283 2023-03-01          fecha_expiracion        16
284 2023-04-01          fecha_expiracion        11
285 2023-05-01          fecha_expiracion         2
286 2023-06-01          fecha_expiracion        18
287 2023-07-01          fecha_expiracion         5
288 2023-08-01          fecha_expiracion         6
289 2023-09-01          fecha_expiracion        13
290 2023-10-01          fecha_expiracion        11
291 2023-11-01          fecha_expiracion        12
292 2023-12-01          fecha_expiracion        63
293 2024-01-01          fecha_expiracion       704
294 2024-02-01          fecha_expiracion        16
295 2024-03-01          fecha_expiracion        19
296 2024-04-01          fecha_expiracion        15
297 2024-05-01          fecha_expiracion        38
298 2024-06-01          fecha_expiracion        37
299 2024-07-01          fecha_expiracion        31
300 2024-08-01          fecha_expiracion        24
301 2024-09-01          fecha_expiracion        52
302 2024-10-01          fecha_expiracion       178
303 2024-11-01          fecha_expiracion        64
304 2024-12-01          fecha_expiracion        86
305 2025-01-01          fecha_expiracion        87
306 2025-02-01          fecha_expiracion       102
307 2025-03-01          fecha_expiracion        82
308 2025-04-01          fecha_expiracion       118
309 2025-05-01          fecha_expiracion        76
310 2025-06-01          fecha_expiracion        76
311 2025-07-01          fecha_expiracion       118
312 2025-08-01          fecha_expiracion       127
313 2025-09-01          fecha_expiracion       134
314 2025-10-01          fecha_expiracion       183
315 2025-11-01          fecha_expiracion       132
316 2025-12-01          fecha_expiracion       131
317 2026-01-01          fecha_expiracion       114
318 2026-02-01          fecha_expiracion       118
319 2026-03-01          fecha_expiracion       125
320 2026-04-01          fecha_expiracion       129
321 2026-05-01          fecha_expiracion       189
322 2026-06-01          fecha_expiracion       140
323 2026-07-01          fecha_expiracion       173
324 2026-08-01          fecha_expiracion        24
325 2021-01-01  fecha_impresion_contrato         1
326 2021-03-01  fecha_impresion_contrato         1
327 2021-12-01  fecha_impresion_contrato         1
328 2022-01-01  fecha_impresion_contrato         6
329 2022-05-01  fecha_impresion_contrato         1
330 2022-09-01  fecha_impresion_contrato         1
331 2022-10-01  fecha_impresion_contrato         1
332 2022-11-01  fecha_impresion_contrato         1
333 2024-02-01  fecha_impresion_contrato         3
334 2024-04-01  fecha_impresion_contrato         1
335 2024-10-01  fecha_impresion_contrato         1
336 2024-11-01  fecha_impresion_contrato         9
337 2024-12-01  fecha_impresion_contrato        11
338 2025-01-01  fecha_impresion_contrato         8
339 2025-02-01  fecha_impresion_contrato         2
340 2025-03-01  fecha_impresion_contrato        16
341 2025-05-01  fecha_impresion_contrato         2
342 2025-06-01  fecha_impresion_contrato         5
343 2025-07-01  fecha_impresion_contrato         1
344 2026-05-01  fecha_impresion_contrato         1
345 2018-03-01            fecha_analisis         4
346 2018-06-01            fecha_analisis         4
347 2018-08-01            fecha_analisis         4
348 2018-09-01            fecha_analisis         2
349 2019-01-01            fecha_analisis         2
350 2019-02-01            fecha_analisis         4
351 2019-03-01            fecha_analisis         4
352 2019-04-01            fecha_analisis         6
353 2019-06-01            fecha_analisis        18
354 2019-07-01            fecha_analisis        11
355 2019-08-01            fecha_analisis         8
356 2019-09-01            fecha_analisis        26
357 2019-10-01            fecha_analisis        10
358 2019-11-01            fecha_analisis        17
359 2019-12-01            fecha_analisis         7
360 2020-01-01            fecha_analisis         2
361 2020-02-01            fecha_analisis        13
362 2020-03-01            fecha_analisis        21
363 2020-05-01            fecha_analisis         2
364 2020-06-01            fecha_analisis         7
365 2020-07-01            fecha_analisis         4
366 2020-08-01            fecha_analisis         2
367 2020-09-01            fecha_analisis         7
368 2020-10-01            fecha_analisis         6
369 2020-11-01            fecha_analisis         2
370 2020-12-01            fecha_analisis         4
371 2021-01-01            fecha_analisis        14
372 2021-02-01            fecha_analisis        11
373 2021-03-01            fecha_analisis        13
374 2021-04-01            fecha_analisis        17
375 2021-05-01            fecha_analisis         8
376 2021-06-01            fecha_analisis        16
377 2021-07-01            fecha_analisis        33
378 2021-08-01            fecha_analisis        20
379 2021-09-01            fecha_analisis        36
380 2021-10-01            fecha_analisis        51
381 2021-11-01            fecha_analisis        36
382 2021-12-01            fecha_analisis        45
383 2022-01-01            fecha_analisis        37
384 2022-02-01            fecha_analisis        58
385 2022-03-01            fecha_analisis        42
386 2022-04-01            fecha_analisis        32
387 2022-05-01            fecha_analisis        38
388 2022-06-01            fecha_analisis        18
389 2022-07-01            fecha_analisis        28
390 2022-08-01            fecha_analisis        25

### Perfil dataframe

In [10]:
import pandas as pd
import numpy as np


def perfilar_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Genera un resumen de calidad y estructura para cada columna
    de un DataFrame.
    """

    filas = len(df)
    resultados = []

    for columna in df.columns:
        serie = df[columna]

        no_nulos = serie.notna().sum()
        nulos = serie.isna().sum()
        unicos = serie.nunique(dropna=True)

        porcentaje_nulos = (
            round(nulos / filas * 100, 2)
            if filas > 0
            else 0
        )

        porcentaje_unicos = (
            round(unicos / no_nulos * 100, 2)
            if no_nulos > 0
            else 0
        )

        ejemplo = serie.dropna().iloc[0] if no_nulos > 0 else None

        resultados.append({
            "variable": columna,
            "tipo_python": str(serie.dtype),
            "filas": filas,
            "no_nulos": no_nulos,
            "nulos": nulos,
            "porcentaje_nulos": porcentaje_nulos,
            "valores_unicos": unicos,
            "porcentaje_unicos": porcentaje_unicos,
            "ejemplo": ejemplo
        })

    perfil = pd.DataFrame(resultados)

    return perfil.sort_values(
        by=["porcentaje_nulos", "valores_unicos"],
        ascending=[False, True]
    ).reset_index(drop=True)


perfil = perfilar_dataframe(df)
with pd.option_context("display.max_rows", None):
    display(perfil)
#display(perfil)

,variable,tipo_python,filas,no_nulos,nulos,porcentaje_nulos,valores_unicos,porcentaje_unicos,ejemplo
0,fecha_contrato,object,4830,0,4830,100.00,0,0.00,None
1,premios,object,4830,0,4830,100.00,0,0.00,None
2,fecha_nif,object,4830,0,4830,100.00,0,0.00,None
3,utm_source,object,4830,0,4830,100.00,0,0.00,None
4,utm_medium,object,4830,0,4830,100.00,0,0.00,None
5,utm_campaign,object,4830,0,4830,100.00,0,0.00,None
6,utm_term,object,4830,0,4830,100.00,0,0.00,None
7,utm_content,object,4830,0,4830,100.00,0,0.00,None
8,codigo_externo_venta,object,4830,0,4830,100.00,0,0.00,None
9,codigo_externo_minuta,object,4830,0,4830,100.00,0,0.00,None
10,motivo_caida,object,4830,0,4830,100.00,0,0.00,None
11,codigo_externo_entrega,object,4830,0,4830,100.00,0,0.00,None
12,fecha_minuta,object,4830,0,4830,100.00,0,0.00,None
13,codigo_externo_anulacion_venta,object,4830,0,4830,100.00,0,0.00,None
14,terminado,object,4830,0,4830,100.00,0,0.00,None
15,estado_personalizado,object,4830,0,4830,100.00,0,0.00,None
16,fecha_devolucion,object,4830,6,4824,99.88,3,50.00,2026-05-26
17,numero_contrato,str,4830,9,4821,99.81,4,44.44,CRUZ0002
18,documento_copropietarios,str,4830,46,4784,99.05,15,32.61,auto-779939
19,fecha_impresion_contrato,object,4830,73,4757,98.49,61,83.56,2024-02-11
20,observacion_devolucion,str,4830,193,4637,96.00,1,0.52,
21,documento_representante,str,4830,224,4606,95.36,57,25.45,17896123
22,excedente,float64,4830,386,4444,92.01,1,0.26,0.0
23,momento_caida,str,4830,416,4414,91.39,2,0.48,proceso
24,documento_conyuge,str,4830,807,4023,83.29,237,29.37,17896123
25,tipo_cronograma,str,4830,940,3890,80.54,1,0.11,Hipotecario
26,flujo_anulacion,str,4830,958,3872,80.17,3,0.31,Anulación
27,fecha_anulacion,object,4830,987,3843,79.57,276,27.96,2022-09-29
28,codigo_unidades_asignadas,str,4830,1108,3722,77.06,384,34.66,EEUU-E19
29,banco,str,4830,3005,1825,37.78,6,0.20,Banco de Crédito del Perú (BCP)
30,aprobador_descuento,str,4830,3104,1726,35.73,22,0.71,ldelsolar
31,nombres_usuario_aprobador,str,4830,3788,1042,21.57,16,0.42,Enzo Villanueva
32,username_aprobador,str,4830,3788,1042,21.57,16,0.42,evillanueva
33,fecha_fin,object,4830,3841,989,20.48,787,20.49,2026-01-30
34,usuario_separacion,str,4830,4085,745,15.42,22,0.54,Enzo Villanueva
35,fecha_analisis,object,4830,4572,258,5.34,1070,23.40,2026-01-30
36,total_pagado,object,4830,4725,105,2.17,80,1.69,0.00
37,total_pendiente,object,4830,4725,105,2.17,231,4.89,0.00
38,estado_nif,str,4830,4752,78,1.61,1,0.02,NO NIF
39,estado_contrato,str,4830,4752,78,1.61,3,0.06,Pendiente
40,fecha_expiracion,object,4830,4752,78,1.61,1006,21.17,2021-09-22
41,flujo_error,object,4830,4798,32,0.66,1,0.02,False
42,nombre_flujo,str,4830,4798,32,0.66,17,0.35,Proceso de entrega
43,apellidos_cliente,str,4830,4824,6,0.12,1352,28.03,Larsen
44,origen_proforma,str,4830,4830,0,0.00,1,0.02,manual
45,moneda,str,4830,4830,0,0.00,1,0.02,PEN
46,tipo_cambio,object,4830,4830,0,0.00,1,0.02,1.000000
47,devolucion,object,4830,4830,0,0.00,1,0.02,0.00
48,penalidad,object,4830,4830,0,0.00,1,0.02,0.00
49,modalidad_contrato,str,4830,4830,0,0.00,2,0.04,Compromiso
50,estado,str,4830,4830,0,0.00,2,0.04,Activo
51,completado,str,4830,4830,0,0.00,2,0.04,Completado
52,tipo,str,4830,4830,0,0.00,2,0.04,ENTREGA
53,proceso_anulacion,str,4830,4830,0,0.00,2,0.04,al iniciar
54,situacion_legal,str,4830,4830,0,0.00,3,0.06,Conyugal
55,total_unidades,int64,4830,4830,0,0.00,4,0.08,2
56,tipo_financiamiento,str,4830,4830,0,0.00,4,0.08,hipotecario
57,nombre,str,4830,4830,0,0.00,5,0.10,Entrega
58,tipo_unidad_principal,str,4830,4830,0,0.00,7,0.14,departamento flat
59,codigo_proyecto,str,4830,4830,0,0.00,17,0.35,EEUU
60,nombre_proyecto,str,4830,4830,0,0.00,17,0.35,Edificio Urbanzen
61,nombres_usuario,str,4830,4830,0,0.00,22,0.46,Yomira Pacheco
62,username,str,4830,4830,0,0.00,22,0.46,ypacheco
63,paso_actual,str,4830,4830,0,0.00,22,0.46,Proceso Terminado
64,usuario_creador,str,4830,4830,0,0.00,26,0.54,JOSUE QUIROGA NAVARRO
65,username_creador,str,4830,4830,0,0.00,26,0.54,jquiroga
66,fecha_actualizacion,object,4830,4830,0,0.00,528,10.93,2026-01-30
67,fecha_proforma,object,4830,4830,0,0.00,748,15.49,2025-09-16
68,fecha_inicio,object,4830,4830,0,0.00,1068,22.11,2026-01-26
69,descuento_venta,object,4830,4830,0,0.00,1109,22.96,77460.00
70,nombres_cliente,str,4830,4830,0,0.00,1182,24.47,Jan Henri
71,documento_cliente,str,4830,4830,0,0.00,1380,28.57,48997555
72,cliente_id,int64,4830,4830,0,0.00,1380,28.57,121739
73,precio_venta,object,4830,4830,0,0.00,1493,30.91,635000.00
74,precio_base_proforma,object,4830,4830,0,0.00,1528,31.64,712460.00
75,codigo_unidad,str,4830,4830,0,0.00,1593,32.98,EEUU-302
76,codigo_proforma,str,4830,4830,0,0.00,1903,39.40,2025-05785
77,proforma_id,int64,4830,4830,0,0.00,1903,39.40,26094
78,id,int64,4830,4830,0,0.00,4752,98.39,21